package com.unicom.entity;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.commentator
     *
     * @mbg.generated
     */
    private String commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.website_url
     *
     * @mbg.generated
     */
    private String websiteUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment_body
     *
     * @mbg.generated
     */
    private String commentBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.reply_body
     *
     * @mbg.generated
     */
    private String replyBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.replier
     *
     * @mbg.generated
     */
    private String replier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.reply_create_time
     *
     * @mbg.generated
     */
    private Date replyCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.is_comments
     *
     * @mbg.generated
     */
    private Boolean isComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.is_deleted
     *
     * @mbg.generated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.blog_id
     *
     * @return the value of comments.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.blog_id
     *
     * @param blogId the value for comments.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.commentator
     *
     * @return the value of comments.commentator
     *
     * @mbg.generated
     */
    public String getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.commentator
     *
     * @param commentator the value for comments.commentator
     *
     * @mbg.generated
     */
    public void setCommentator(String commentator) {
        this.commentator = commentator == null ? null : commentator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.email
     *
     * @return the value of comments.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.email
     *
     * @param email the value for comments.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.website_url
     *
     * @return the value of comments.website_url
     *
     * @mbg.generated
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.website_url
     *
     * @param websiteUrl the value for comments.website_url
     *
     * @mbg.generated
     */
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl == null ? null : websiteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment_body
     *
     * @return the value of comments.comment_body
     *
     * @mbg.generated
     */
    public String getCommentBody() {
        return commentBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment_body
     *
     * @param commentBody the value for comments.comment_body
     *
     * @mbg.generated
     */
    public void setCommentBody(String commentBody) {
        this.commentBody = commentBody == null ? null : commentBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.create_time
     *
     * @return the value of comments.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.create_time
     *
     * @param createTime the value for comments.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.reply_body
     *
     * @return the value of comments.reply_body
     *
     * @mbg.generated
     */
    public String getReplyBody() {
        return replyBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.reply_body
     *
     * @param replyBody the value for comments.reply_body
     *
     * @mbg.generated
     */
    public void setReplyBody(String replyBody) {
        this.replyBody = replyBody == null ? null : replyBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.replier
     *
     * @return the value of comments.replier
     *
     * @mbg.generated
     */
    public String getReplier() {
        return replier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.replier
     *
     * @param replier the value for comments.replier
     *
     * @mbg.generated
     */
    public void setReplier(String replier) {
        this.replier = replier == null ? null : replier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.reply_create_time
     *
     * @return the value of comments.reply_create_time
     *
     * @mbg.generated
     */
    public Date getReplyCreateTime() {
        return replyCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.reply_create_time
     *
     * @param replyCreateTime the value for comments.reply_create_time
     *
     * @mbg.generated
     */
    public void setReplyCreateTime(Date replyCreateTime) {
        this.replyCreateTime = replyCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.is_comments
     *
     * @return the value of comments.is_comments
     *
     * @mbg.generated
     */
    public Boolean getIsComments() {
        return isComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.is_comments
     *
     * @param isComments the value for comments.is_comments
     *
     * @mbg.generated
     */
    public void setIsComments(Boolean isComments) {
        this.isComments = isComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.is_deleted
     *
     * @return the value of comments.is_deleted
     *
     * @mbg.generated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.is_deleted
     *
     * @param isDeleted the value for comments.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}