package com.unicom.entity;

import java.util.Date;

public class Follow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follower_id
     *
     * @mbg.generated
     */
    private Integer followerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.followed_id
     *
     * @mbg.generated
     */
    private Integer followedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.is_liked
     *
     * @mbg.generated
     */
    private Boolean isLiked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.is_cancelled
     *
     * @mbg.generated
     */
    private Boolean isCancelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.id
     *
     * @return the value of follow.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.id
     *
     * @param id the value for follow.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follower_id
     *
     * @return the value of follow.follower_id
     *
     * @mbg.generated
     */
    public Integer getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follower_id
     *
     * @param followerId the value for follow.follower_id
     *
     * @mbg.generated
     */
    public void setFollowerId(Integer followerId) {
        this.followerId = followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.followed_id
     *
     * @return the value of follow.followed_id
     *
     * @mbg.generated
     */
    public Integer getFollowedId() {
        return followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.followed_id
     *
     * @param followedId the value for follow.followed_id
     *
     * @mbg.generated
     */
    public void setFollowedId(Integer followedId) {
        this.followedId = followedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.blog_id
     *
     * @return the value of follow.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.blog_id
     *
     * @param blogId the value for follow.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.is_liked
     *
     * @return the value of follow.is_liked
     *
     * @mbg.generated
     */
    public Boolean getIsLiked() {
        return isLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.is_liked
     *
     * @param isLiked the value for follow.is_liked
     *
     * @mbg.generated
     */
    public void setIsLiked(Boolean isLiked) {
        this.isLiked = isLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.is_cancelled
     *
     * @return the value of follow.is_cancelled
     *
     * @mbg.generated
     */
    public Boolean getIsCancelled() {
        return isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.is_cancelled
     *
     * @param isCancelled the value for follow.is_cancelled
     *
     * @mbg.generated
     */
    public void setIsCancelled(Boolean isCancelled) {
        this.isCancelled = isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.create_time
     *
     * @return the value of follow.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.create_time
     *
     * @param createTime the value for follow.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}