package com.unicom.entity;

import java.util.Date;

public class Follow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follower_name
     *
     * @mbg.generated
     */
    private String followerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.followed_name
     *
     * @mbg.generated
     */
    private String followedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.blog_id
     *
     * @mbg.generated
     */
    private Integer blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.is_liked
     *
     * @mbg.generated
     */
    private Byte isLiked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.is_cancelled
     *
     * @mbg.generated
     */
    private Boolean isCancelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.id
     *
     * @return the value of follow.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.id
     *
     * @param id the value for follow.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follower_name
     *
     * @return the value of follow.follower_name
     *
     * @mbg.generated
     */
    public String getFollowerName() {
        return followerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follower_name
     *
     * @param followerName the value for follow.follower_name
     *
     * @mbg.generated
     */
    public void setFollowerName(String followerName) {
        this.followerName = followerName == null ? null : followerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.followed_name
     *
     * @return the value of follow.followed_name
     *
     * @mbg.generated
     */
    public String getFollowedName() {
        return followedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.followed_name
     *
     * @param followedName the value for follow.followed_name
     *
     * @mbg.generated
     */
    public void setFollowedName(String followedName) {
        this.followedName = followedName == null ? null : followedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.blog_id
     *
     * @return the value of follow.blog_id
     *
     * @mbg.generated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.blog_id
     *
     * @param blogId the value for follow.blog_id
     *
     * @mbg.generated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.is_liked
     *
     * @return the value of follow.is_liked
     *
     * @mbg.generated
     */
    public Byte getIsLiked() {
        return isLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.is_liked
     *
     * @param isLiked the value for follow.is_liked
     *
     * @mbg.generated
     */
    public void setIsLiked(Byte isLiked) {
        this.isLiked = isLiked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.is_cancelled
     *
     * @return the value of follow.is_cancelled
     *
     * @mbg.generated
     */
    public Boolean getIsCancelled() {
        return isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.is_cancelled
     *
     * @param isCancelled the value for follow.is_cancelled
     *
     * @mbg.generated
     */
    public void setIsCancelled(Boolean isCancelled) {
        this.isCancelled = isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.create_time
     *
     * @return the value of follow.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.create_time
     *
     * @param createTime the value for follow.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.update_time
     *
     * @return the value of follow.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.update_time
     *
     * @param updateTime the value for follow.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}